# Generated by Django 6.0.3 on 2026-03-11 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capital', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tasa_anual', models.DecimalField(decimal_places=2, help_text='Porcentaje, ej. 15.00', max_digits=5)),
                ('base_calculo', models.IntegerField(choices=[(365, '365 días'), (360, '360 días')], default=365)),
                ('porcentaje_factura', models.DecimalField(decimal_places=2, default=100, help_text='% que se factura, el resto es pago externo', max_digits=5)),
                ('fecha_inicio', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('por_vencer', 'Por Vencer'), ('vencido', 'Vencido')], default='activo', max_length=15)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Inversión',
                'verbose_name_plural': 'Inversiones',
            },
        ),
        migrations.CreateModel(
            name='Inversionista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contribuyente', models.CharField(choices=[('fisica', 'Persona Física'), ('moral', 'Persona Moral')], default='fisica', max_length=10)),
                ('es_entidad_financiera', models.BooleanField(default=False)),
                ('nombre_completo', models.CharField(max_length=300)),
                ('nacionalidad', models.CharField(default='Mexicana', max_length=100)),
                ('curp', models.CharField(blank=True, max_length=18)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('tipo_documento', models.CharField(choices=[('ine', 'INE / Credencial de Elector'), ('pasaporte', 'Pasaporte'), ('cedula', 'Cédula Profesional'), ('otro', 'Otro')], default='ine', max_length=20)),
                ('numero_documento', models.CharField(blank=True, max_length=50)),
                ('estado_civil', models.CharField(choices=[('soltero', 'Soltero(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viudo', 'Viudo(a)')], default='soltero', max_length=15)),
                ('calle', models.CharField(blank=True, max_length=300)),
                ('ciudad', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=100)),
                ('codigo_postal', models.CharField(blank=True, max_length=10)),
                ('rfc', models.CharField(blank=True, max_length=13)),
                ('regimen_fiscal', models.CharField(default='Régimen de Intereses', max_length=200)),
                ('nombre_fiscal', models.CharField(blank=True, max_length=300)),
                ('pais_fiscal', models.CharField(default='México', max_length=100)),
                ('estado_fiscal', models.CharField(blank=True, max_length=100)),
                ('cp_fiscal', models.CharField(blank=True, max_length=10)),
                ('banco', models.CharField(blank=True, choices=[('bbva', 'BBVA Bancomer'), ('banorte', 'Banorte'), ('hsbc', 'HSBC'), ('santander', 'Santander'), ('banamex', 'Banamex'), ('otro', 'Otro')], max_length=20)),
                ('clabe', models.CharField(blank=True, max_length=18)),
            ],
            options={
                'verbose_name': 'Inversionista',
                'verbose_name_plural': 'Inversionistas',
            },
        ),
        migrations.CreateModel(
            name='Promotor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Promotor',
                'verbose_name_plural': 'Promotores',
            },
        ),
        migrations.CreateModel(
            name='EstadoDeCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('dias_periodo', models.IntegerField()),
                ('interes_bruto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('isr', models.DecimalField(decimal_places=2, max_digits=14)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=14)),
                ('interes_neto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('pago_externo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_pagar', models.DecimalField(decimal_places=2, max_digits=14)),
                ('estado', models.CharField(choices=[('generado', 'Generado'), ('enviado', 'Enviado'), ('pendiente', 'Pendiente')], default='pendiente', max_length=15)),
                ('fecha_generado', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True)),
                ('inversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados_de_cuenta', to='inversiones.inversion')),
            ],
            options={
                'verbose_name': 'Estado de Cuenta',
                'verbose_name_plural': 'Estados de Cuenta',
            },
        ),
        migrations.AddField(
            model_name='inversion',
            name='inversionista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inversiones', to='inversiones.inversionista'),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('transferencia', 'Transferencia bancaria'), ('efectivo', 'Efectivo'), ('sindicato', 'Sindicato'), ('otro', 'Otro')], max_length=20)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pagado', 'Pagado'), ('pendiente', 'Pendiente')], default='pendiente', max_length=15)),
                ('folio', models.CharField(blank=True, max_length=30)),
                ('notas', models.TextField(blank=True)),
                ('confirmado_por', models.CharField(blank=True, max_length=200)),
                ('estado_de_cuenta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='inversiones.estadodecuenta')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.AddField(
            model_name='inversionista',
            name='promotor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inversionistas', to='inversiones.promotor'),
        ),
        migrations.CreateModel(
            name='Prospecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=300)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('monto_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('etapa', models.CharField(choices=[('inicial', 'Contacto Inicial'), ('seguimiento', 'En Seguimiento'), ('listo', 'Listo para Alta')], default='inicial', max_length=15)),
                ('notas', models.TextField(blank=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('convertido', models.BooleanField(default=False)),
                ('inversionista', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospecto_origen', to='inversiones.inversionista')),
                ('promotor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospectos', to='inversiones.promotor')),
            ],
            options={
                'verbose_name': 'Prospecto',
                'verbose_name_plural': 'Prospectos',
            },
        ),
    ]
