# Generated by Django 6.0.3 on 2026-04-04 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inversiones', '0002_honeypotattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('calculo', 'Error en cálculo'), ('visual', 'Error visual / diseño'), ('formulario', 'Formulario no guarda'), ('email', 'Error en envío de correo'), ('carga', 'Página no carga / lenta'), ('otro', 'Otro')], max_length=20)),
                ('pagina', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('esperado', models.TextField(blank=True)),
                ('url_actual', models.URLField(blank=True)),
                ('usuario', models.CharField(blank=True, max_length=200)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('resuelto', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Reporte de Error',
                'verbose_name_plural': 'Reportes de Errores',
                'ordering': ['-fecha'],
            },
        ),
    ]
