# Generated by Django 6.0.3 on 2026-04-04 02:04

import djrichtextfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inversiones', '0003_bugreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bugreport',
            name='descripcion',
            field=djrichtextfield.models.RichTextField(),
        ),
        migrations.AlterField(
            model_name='bugreport',
            name='esperado',
            field=djrichtextfield.models.RichTextField(blank=True),
        ),
    ]
