# Generated by Django 6.0.3 on 2026-04-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inversiones', '0004_alter_bugreport_descripcion_alter_bugreport_esperado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inversionista',
            name='curp',
            field=models.CharField(blank=True, max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='inversionista',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, unique=True),
        ),
    ]
