# Generated by Django 6.0.3 on 2026-04-13 00:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inversiones', '0006_movimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadodecuenta',
            name='inversionista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estados_de_cuenta', to='inversiones.inversionista'),
        ),
        migrations.AlterField(
            model_name='estadodecuenta',
            name='inversion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estados_de_cuenta', to='inversiones.inversion'),
        ),
        migrations.AlterUniqueTogether(
            name='estadodecuenta',
            unique_together={('inversionista', 'periodo_inicio')},
        ),
    ]
