# Generated by Django 6.0.3 on 2026-04-18 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inversiones', '0007_estadodecuenta_inversionista_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inversion',
            name='porcentaje_factura',
            field=models.DecimalField(decimal_places=6, default=100, help_text='% que se factura, el resto es pago externo', max_digits=10),
        ),
    ]
