# Generated by Django 6.0.3 on 2026-04-18 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inversiones', '0008_alter_inversion_porcentaje_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='inversionista',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inversionista',
            name='fecha_eliminado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
