# Generated by Django 6.0.3 on 2026-05-16 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inversiones', '0009_inversionista_eliminado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionDismissed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_dismissed', models.DateField(auto_now_add=True)),
                ('inversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_dismissed', to='inversiones.inversion')),
            ],
            options={
                'verbose_name': 'Notificación Descartada',
                'verbose_name_plural': 'Notificaciones Descartadas',
                'unique_together': {('inversion', 'fecha_dismissed')},
            },
        ),
    ]
