# Generated by Django 6.0.3 on 2026-05-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inversiones', '0010_notificaciondismissed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotor',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
