# Generated by Django 6.0.3 on 2026-05-21 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inversiones', '0011_alter_promotor_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inversionista',
            name='curp',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='inversionista',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
