# Generated by Django 6.0.3 on 2026-05-29 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inversiones', '0012_alter_inversionista_curp_alter_inversionista_rfc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inversion',
            name='porcentaje_factura',
            field=models.DecimalField(decimal_places=5, default=100, help_text='% que se factura, el resto es pago externo', max_digits=10),
        ),
    ]
