# Generated by Django 6.0.3 on 2026-05-29 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inversiones', '0013_alter_inversion_porcentaje_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='inversionista',
            name='periodicidad_pago',
            field=models.IntegerField(choices=[(28, '28 días'), (30, '30 días')], default=28),
        ),
    ]
