# Generated by Django 6.0.3 on 2026-06-23 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inversiones', '0014_inversionista_periodicidad_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='inversionista',
            name='dias_cierre_fijo',
            field=models.PositiveIntegerField(blank=True, help_text='Si se define, el cierre SIEMPRE usa estos días para este inversionista, ignorando las fechas globales.', null=True),
        ),
    ]
