# Generated by Django 6.0.3 on 2026-08-19 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inversiones', '0015_inversionista_dias_cierre_fijo'),
    ]

    operations = [
        migrations.AddField(
            model_name='inversion',
            name='numero_renovacion',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inversion',
            name='renovacion_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renovaciones', to='inversiones.inversion'),
        ),
    ]
